import type { LocalizedText } from "@/lib/types";

/** Body copy for the /about page. */
export const aboutParagraphs: LocalizedText[] = [
  {
    en: "Next Play helps athletes, parents, coaches, athletic trainers, and clinicians find the next safest step after a sports injury — in plain language, in English or Spanish.",
    es: "Next Play ayuda a atletas, padres, entrenadores, entrenadores atléticos y profesionales médicos a encontrar el siguiente paso más seguro después de una lesión deportiva — en lenguaje sencillo, en inglés o español.",
  },
  {
    en: "It was created by a sports medicine physician. Next Play does not diagnose and does not replace medical care. Instead, it organizes what you already know about an injury and points you toward the right level of care: emergency, urgent same-day, a scheduled sports medicine visit, or careful monitoring.",
    es: "Fue creado por un médico de medicina deportiva. Next Play no diagnostica ni reemplaza la atención médica. En cambio, organiza lo que usted ya sabe sobre una lesión y lo orienta hacia el nivel de atención adecuado: emergencia, urgencia el mismo día, una visita programada de medicina deportiva o una vigilancia cuidadosa.",
  },
  {
    en: "Every recommendation is generated by transparent, rules-based logic that a physician can review and edit — not by a black-box algorithm. The goal is simple: clearer injury decisions and a safer return to play.",
    es: "Cada recomendación se genera con una lógica transparente basada en reglas que un médico puede revisar y editar — no con un algoritmo opaco. El objetivo es simple: decisiones más claras sobre las lesiones y un regreso al juego más seguro.",
  },
];

/** Title + body copy for the /disclaimer page. */
export const disclaimerTitle: LocalizedText = {
  en: "Important safety information",
  es: "Información de seguridad importante",
};

export const disclaimerParagraphs: LocalizedText[] = [
  {
    en: "Next Play provides general health information and injury navigation guidance only. It is not a medical device and does not provide a diagnosis.",
    es: "Next Play solo ofrece información general de salud y orientación para la navegación de lesiones. No es un dispositivo médico y no proporciona un diagnóstico.",
  },
  {
    en: "Next Play cannot clear anyone to return to play and does not replace evaluation, diagnosis, or treatment by a qualified healthcare professional.",
    es: "Next Play no puede autorizar a nadie a volver a jugar y no reemplaza la evaluación, el diagnóstico ni el tratamiento de un profesional de la salud calificado.",
  },
  {
    en: "Always seek the advice of a physician, athletic trainer, or other qualified provider with any questions about an injury. Never disregard professional medical advice, or delay seeking it, because of something you read in this app.",
    es: "Busque siempre el consejo de un médico, entrenador atlético u otro profesional calificado ante cualquier duda sobre una lesión. Nunca ignore el consejo médico profesional, ni retrase buscarlo, por algo que haya leído en esta aplicación.",
  },
  {
    en: "If you think there may be a medical emergency, call 911 (or your local emergency number) immediately.",
    es: "Si cree que puede haber una emergencia médica, llame al 911 (o a su número de emergencia local) de inmediato.",
  },
  {
    en: "Using Next Play does not create a doctor–patient relationship.",
    es: "El uso de Next Play no crea una relación médico–paciente.",
  },
];
