/**
 * Generate an offline service worker for the static export.
 * Run AFTER `next build` (export), with BASE_PATH matching the deploy:
 *   BASE_PATH=/next-play node scripts/generate-sw.mjs
 *
 * It scans out/ and precaches every page + asset, so once the app has loaded
 * online it works fully offline (the triage engine is deterministic and needs
 * no network) — important for a sideline with poor signal.
 */
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

const OUT = "out";
const BASE = process.env.BASE_PATH || "";

function walk(dir) {
  const found = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) found.push(...walk(p));
    else found.push(p);
  }
  return found;
}

const files = walk(OUT)
  .map((f) => relative(OUT, f).split(sep).join("/"))
  .filter((f) => f !== "sw.js" && !f.endsWith(".map"));

const urls = new Set();
for (const f of files) {
  if (f === "index.html") urls.add(`${BASE}/`);
  else if (f.endsWith("/index.html"))
    urls.add(`${BASE}/${f.slice(0, -"index.html".length)}`);
  else urls.add(`${BASE}/${f}`);
}
const precache = [...urls];

// Content-derived cache version so a new deploy busts the old cache.
let h = 0;
const joined = precache.join("|");
for (let i = 0; i < joined.length; i++) h = (h * 31 + joined.charCodeAt(i)) >>> 0;
const cacheName = `nextplay-${h.toString(16)}`;

const sw = `// Auto-generated by scripts/generate-sw.mjs — do not edit by hand.
const CACHE = ${JSON.stringify(cacheName)};
const PRECACHE = ${JSON.stringify(precache)};
const OFFLINE_URL = ${JSON.stringify(`${BASE}/`)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => Promise.allSettled(PRECACHE.map((u) => cache.add(u))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // Navigations: network-first (fresh when online), fall back to cache offline.
  if (req.mode === "navigate") {
    event.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
          return res;
        })
        .catch(() =>
          caches.match(req, { ignoreSearch: true }).then((m) => m || caches.match(OFFLINE_URL))
        )
    );
    return;
  }

  // Assets: cache-first, then network (and cache the result).
  event.respondWith(
    caches.match(req, { ignoreSearch: true }).then((cached) =>
      cached ||
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
          return res;
        })
        .catch(() => cached)
    )
  );
});
`;

writeFileSync(join(OUT, "sw.js"), sw);
console.log(`Generated out/sw.js — cache ${cacheName}, ${precache.length} precached URLs`);
